# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
pt-br:
  languageCode: pt-br
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/pt-br

# Uncomment the lines below to configure your website in a second language.
en:
 languageCode: en-us
 contentDir: content/en
 title: Igor Laltuf
 params:
   description:
 menu:
   main:
     - name: About
       url: '#about'
       weight: 10
     - name: Software | Data
       url: project/
       weight: 20
     - name: Publications
       url: publication/
       weight: 30
     - name: Events
       url: event/
       weight: 40
     - name: Blog
       url: post/
       weight: 60
